#!/usr/bin/env python3
import sys, os, re, subprocess

####
## Print in Color

BLACK = "\033[0;30m"
RED = "\033[0;31m"
GREEN = "\033[0;32m"
BROWN = "\033[0;33m"
BLUE = "\033[0;34m"
PURPLE = "\033[0;35m"
CYAN = "\033[0;36m"
LIGHT_GRAY = "\033[0;37m"
YELLOW = "\033[0;33m"
DARK_GRAY = "\033[1;30m"
LIGHT_RED = "\033[1;31m"
LIGHT_GREEN = "\033[1;32m"
LIGHT_YELLOW = "\033[1;33m"
LIGHT_BLUE = "\033[1;34m"
LIGHT_PURPLE = "\033[1;35m"
LIGHT_CYAN = "\033[1;36m"
LIGHT_WHITE = "\033[1;37m"
BOLD = "\033[1m"
FAINT = "\033[2m"
ITALIC = "\033[3m"
UNDERLINE = "\033[4m"
BLINK = "\033[5m"
NEGATIVE = "\033[7m"
CROSSED = "\033[9m"
END = "\033[0m"
DANGER = RED+BOLD+NEGATIVE+BLINK


def colorize(line):
    color_patterns = {
        'error|fail(ed)?':RED,
        'warn(ing)?':YELLOW,
        'notice|INFO':CYAN,
        '(SUCCESS|success(fully)?)':GREEN,
        '(?<=" )(5[0|1][0-9])(?= )':RED,                                        # 500
        '(?<=" )(4[0|1][0-9])(?= )':YELLOW,                                     # 400
        '(?<=" )(3[0|1][0-9])(?= )':YELLOW,                                     # 300
        '(?<=" )(2[0|1][0-9])(?= )':GREEN,                                      # 200
        '(?<=")(GET|HEAD|POST|DELETE|PUT|CONNECT|OPTIONS|TRACE|PATCH|PROPFIND)(?= \/)':'inherit',  # method
        '\[(([A-Za-z]{3} ){2}[0-9]{2} )(.*?)\]':FAINT,                          # time
        '\[([0-9]{2}\/[A-Za-z]{3})(.*?)\]':FAINT,                               # time 2
        '[A-Za-z]{3} [0-9]{2} ([0-9]{2}:?){3}':FAINT,                           # time 3
        '([0-9]{2}-?){4} ([0-9]{2}:?){3}':FAINT,                                # time 4
        '(?<= )[A-Za-z]{3,9}(.+?)\]:':FAINT,                               # process 
        'HTTP/[0-3]\.[0-9]':FAINT,                                              # HTTPS/1.0
        r'((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}':CYAN,                     # IP
        '(?<=port )[0-9]{1,6}':CYAN,
        '(?<= )([a-zA-Z0-9_-]+)(B|b)ot':CYAN,                                   # Bots
        '(P|p)ython|curl|PostmanRuntime|Insomnia':CYAN,                         # Script
#        '(Mozilla|Chrome|Opera|Edge|Firefox|Safari|Samsung|WebView)\/':CYAN,    # UA
        '(setup-config\.php|config\.json|wp-config\.php|\.git|chan.php)':DANGER, #dangerous exact
        '(install|debug|DirBuster|GoBuster|fuzz|hackwp)':DANGER,                # dangerous part
        '(?<= \/)(.*?)\.(env|log)(?= )':DANGER,                                 # dangerous ending
        '(render_element|php_code)':DANGER,                                     # dangerous bricks & breakdance 
        '\/uploads(.*?)\.(php[0-9]?|phtml|py|pl|cgi|jsp|asp|sh)':DANGER,        # dangerous pattern 
        '(root)':BOLD+UNDERLINE+PURPLE,                                     # dangerous bricks & breakdance 
        '(granted|session opened|enabled|Accepted(.+)for|ready)':GREEN,                                     # dangerous bricks & breakdance 
        '(File(.+)exist:|(Connection|session) closed|disabled|Disconnected from|forward(ed)?)':YELLOW,                                     # dangerous bricks & breakdance 
        '(invalid|block(ed)?)':RED,                                     # dangerous bricks & breakdance 
    }
    color_line = line
    last_color = False
    for pattern, color in color_patterns.items():   # iterate
        txt = re.search(pattern, line)
        if txt:                                     # if match
            color = last_color if color == 'inherit' else color
            color_line = re.sub(pattern, color+txt[0]+END, color_line)
            last_color = color if not last_color else last_color
#            print(color_line)

    return color_line

# Prepend [ WHO ] to the line
def who(line):
    # Bots and Scripts
    patterns = {
        '([a-zA-Z0-9_-]+)(B|b)ot':'['+CYAN+BOLD+'BOT'+END+']',
        '(P|p)ython|curl|PostmanRuntime|Insomnia':'['+CYAN+BOLD+'SCR'+END+']',
    }

    for pattern, txt in patterns.items():
        if re.search(pattern, line):
            return txt+' '+line

    # Local host 
    ip = re.search(r'((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}', line)
    if ip:
        private = re.search('(^127\.)|(^192\.168\.)|(^10\.)|(^172\.1[6-9]\.)|(^172\.2[0-9]\.)|(^172\.3[0-1]\.)|(^::1$)|(^[fF][cCdD])', ip[0])
    else:
        private = False

    who = '['+PURPLE+BOLD+'YOU'+END+']' if private else '['+LIGHT_WHITE+BOLD+'---'+END+']'
    return who+' '+line

# Remove first arg (script name)
args = sys.argv[1:]

try:
    cmd = ["tail", *args]
    with subprocess.Popen(cmd, stdout=subprocess.PIPE, bufsize=1, universal_newlines=True) as p:
        for line in p.stdout:
            line = colorize(line)
            line = who(line)
            print(line, end='') # process line here

    if p.returncode != 0:
        raise subprocess.CalledProcessError(p.returncode, p.args)

except(KeyboardInterrupt):
    exit()
